### ISSUE TITLE
NumberFormatException

### ISSUE THREAD

**Issue by ADernikas** [CytoDev/FrequencyCalculator#9]
The app crashes when you try to enter a number in a field if you have a phone with Dutch locale.

**Comment by cytodev** [comment]
Hey Alexander, thanks for bringing this to my attention! I'll make sure to fix this issue as soon as possible!

**Comment by cytodev** [comment]
## A possible fix to the above issue:

```java
// add these to imports
import java.text.NumberFormat;
import java.util.Locale;

// change this method
public String clipDecimals(double decimalNumber) {
    // pre-decimalFormat code
    // ...

    Locale        locale        = Locale.getDefault(Locale.Category.FORMAT);
    NumberFormat  numberFormat  = NumberFormat.getNumberInstance(locale);
    DecimalFormat decimalFormat = new DecimalFormat(numberFormat);
    Number        number        = numberFormat.parse(decimalFormat.format(decimalNumber));

    // more code
    // ...

    if(Double.parseDouble(df.format(number)) == 0.000) { // Exception thrown here
        // more code
        // ...
    }

    // post-crash code
    // ..
}
```

The only issue being that Android doesn't implement default locales until API level 24 (Android 7.0 Nougat), and [I already felt bad for dropping support of levels 14 and 15](/cytodev/frequencycalculator/commits/55bc81f0f9c88e7a03451b2d8c14507fb5019fb8)

According to Oracle, this is [not a bug but a feature enhancement](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=7073906)...

## Reading material:
[This post](https://www.baeldung.com/java-decimalformat) has an interesting take on the issue.
[This accepted answer](https://stackoverflow.com/questions/10584948/doubles-commas-and-dots) is API level 29 and up. `DecimalFormatSymbols` is also suggested, but once again API level 29 and up (why is Android so late to the localization party? -- Seriously, all [this shit](https://memorynotfound.com/format-a-decimal-number-with-decimalformat-example/) is API 20+!?)
[This accepted answer](https://stackoverflow.com/questions/4323599/best-way-to-parsedouble-with-comma-as-decimal-separator) may have some leads for earlier API levels

## Current idea:
Honestly, no clue. I've tried solving it the clean way, and I've tried solving it the easy way -- but the locales just keep fucking me over on this one... You might think that you can just replace the commas with periods and format the number after the fact, but no; boom, you've got another locale issue up your ass. Ditching this issue is also not an option seeing how not a single person can agree on a number standardization ([and dates, for that matter](https://en.wikipedia.org/wiki/ISO_8601))

**Comment by cytodev** [comment]
Fixed the issue by defaulting the number format to US standards

**Comment by cytodev** [comment]
Hey @ADernikas, Could you check if the issue still persists after the latest update?

**Comment by ADernikas** [comment]
The latest update fixed the issue.
